Blog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.Blog, name='blog'),
    path('category/<int:category_id>/',views.category, name='category')
]

Shoppingcart/urls.py
from django.urls import include, path
from .import views
from django.conf import settings
from django.conf.urls.static import static

# avoid collisions with other urls (namespace)
app_name = 'shopc'

urlpatterns = [
    
    path('add/<int:product_id>/', views.add_product , name='add'),
    path('delete/<int:product_id>/', views.delete_product , name='delete'),
    path('substract/<int:product_id>/', views.substract_product , name='substract'),
    path('clean/<int:product_id>/', views.clean_products , name='clean'),


   
]

Store/urls.py
from django.urls import include, path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.store, name='store'),

   
]

projectweb/urls.py
from django.contrib import admin
from django.urls import path, include





urlpatterns = [
    path('admin/', admin.site.urls),
    #path('ProjectWebApp/', include('ProjectWebApp.urls')),
    path('', include('ProjectWebApp.urls')),
    path('services/', include('Services.urls')),
    path('blog/', include('Blog.urls')),
    path('contact/', include('Contact.urls')),
    path('store/', include('Store.urls')),
    path('shop/', include('Shoppingcart.urls')),
    path('auth/', include('authentication.urls')),
    path('process_order/', include('orders.urls')),
]

Store/models.py
from django.db import models

# Create your models here.





class CategoryProd(models.Model):

    name = models.CharField(max_length=50)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)

    
    class Meta():
        verbose_name = 'categoria_prod'
        verbose_name_plural = 'categorias_prod'
    
    def __str__(self) -> str:
        return self.name
    

class Product(models.Model):
    image = models.ImageField(upload_to='store', null=True, blank=True)
    name = models.CharField(max_length=80)
    price = models.FloatField()
    disponibility = models.BooleanField(default=True)
    category = models.ForeignKey(CategoryProd, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)

    class Meta():
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
    
    def __str__(self) -> str:
        return self.name
    

Store/views.py
from django.shortcuts import render
from Store.models import Product

# Create your views here.
def store(request):
    products = Product.objects.all()

    return render(request, 'store/store.html',{"products":products})

Store/templates/cart/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Shopping cart
            </th>
        </tr>

        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Sub-total</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.sh_cart.items %}
            {% for key,value in request.session.sh_cart.items %}

                <tr class="text-center"> 
                    <td> {{value.product_name}} </td>
                    <td> {{value.product_quantity}} </td>
                    <td> 
                        <!-- calling urls from shopping cart -->
                        <a href="{% url 'shopc:add' value.product_id%}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'shopc:substract' value.product_id%}" class="btn btn-sm btn-danger">-</a>
                        {{value.product_price}}
                    </td>
                </tr>
            {% endfor %}
            
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">No products</div>
                </td>
            </tr>

            
        {% endif %}
        
    </tbody>
    <tfoot>
        <tr>
            <!-- call the context_processor's function -->
            <td colspan="3">total: Q. {{total_cart}}</td>
        </tr>
        {% if request.session.sh_cart.items %}
            <tr>
                <td colspan="3" style="text-align: center; color: white;">
                    <a href="{% url 'process_order'%}" class="btn btn-success">Pagar</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>
</table>